config/routes.rb
Rails.application.routes.draw do
  #resources :posts
  resources :users do
    resources :posts
  end
  get "login", to: redirect("/auth/google_oauth2"), as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  get "auth/required", to: "sessions#new"
  get "mypage", to: "users#mypage"
  get "unauthorized", to: "sessions#unauthorized"
  root to: "posts#facepage"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  validates :title, :content, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :name, presence: true, uniqueness: true

  def self.find_or_create_from_auth_hash(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.email = auth.info.email
      user.picture = auth.info.image
      user.save!
    end
  end

  def to_s
    first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :user_signed_in?

  def authenticate
    redirect_to :controller => "sessions", :action => "unauthorized" unless user_signed_in?
  end

  def authorizeOnlyAdmin
    redirect_to :controller => "sessions", :action => "unauthorized" unless admin_signed_in?
  end

  def admin_signed_in?
    user_signed_in? and current_user.is_admin
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    # converts current_user to a boolean by negating the negation
    !!current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:new, :index, :create, :edit, :update, :destroy]
  before_action :authorize_post_change, only: [:edit, :destroy]
  before_action :authorize_post_view, only: [:show]

  # GET /posts
  # GET /posts.json
  def index
    if admin_signed_in?
      @posts = Post.all.order(created_at: :desc)
    elsif user_signed_in?
      @posts = Post.where(:user_id => current_user.id).order(created_at: :desc)
    else
      @posts = Post.where("is_public=? and published_at<?", true, DateTime.now).order(created_at: :desc)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def facepage
    if admin_signed_in?
      @posts = Post.all
    elsif user_signed_in?
      @posts = Post.where("published_at<=?", DateTime.now)
    else
      @posts = Post.where("is_public=? and published_at<?", true, DateTime.now)
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :is_public, :published_at, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def unauthorized
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def mypage
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:provider, :uid, :email, :first_name, :last_name, :picture, :is_admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end

  def link_to_unless_current(body, url, classes)
    unless current_page?(url)
      link_to body, url, classes
    else
      body
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def authorize_post_change
    unless admin_signed_in?
      @post = Post.find(params[:id])
      unless @post.user_id == current_user.id
        redirect_to :controller => "sessions", :action => "unauthorized"
      end
    end
  end

  def authorize_post_view
    unless admin_signed_in?
      @post = Post.find(params[:id])
      unless @post.is_public or @post.user_id == current_user.id
        redirect_to :controller => "sessions", :action => "unauthorized"
      end
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xapper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" type="image/x-icon" href="<%= asset_pack_path 'media/images/favicon.ico' %>" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <%= render 'shared/navbar' %>
      <p>
        <%= yield %>
      </p>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <strong><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</strong>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :title, class: 'form-control', placeholder: "Title" %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :is_public %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.text_field :published_at %>
  </div>

  <div class="field">
    <%= form.rich_text_area :content, class: 'form-control', placeholder: "Tell your story" %>
  </div>  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h3>Editing Post</h3>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/facepage.html.erb
<% @posts.each do |post| %>
    <h3><%= link_to post.title[0..50], post, :style => "text-decoration: none;" %></h3>
    <small style="color: grey;"> 
        <%= post.created_at %>
        <%= link_to "#{post.user.first_name}", {action: 'mypage', controller: 'users'} %>
    </small>
    <p>
        <%= @body = post.content.to_plain_text[0..400] %>
        <small><%= link_to "...more", post unless @body.length < 400 %></small>
    </p>
<% end %>

app/views/posts/index.html.erb
<p id="notice" class="<%= 'alert alert-success' if notice %>"><%= notice %></p>

<h3>Manage Posts</h3>

<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th colspan="3" style="width:  10%"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to "#{post.title}", post %></td>
        <td>
          <%= link_to image_tag(post.user.picture, class: "rounded", size: 25), 
          {action: 'mypage', controller: 'users'} %>
        </td>
        <td>
          <% if post.is_public? %>
            <span class="fa fa-unlock" style="color:green"></span>
          <% else %>
            <span class="fa fa-lock"></span>
          <% end %>
        </td>
        <td><%= link_to '<i class="fa fa-edit" style="color:blue"></i>'.html_safe, 
            edit_post_path(post), :title => "Edit post" %>
        </td>
        <td><%= link_to '<i class="fa fa-trash" style="color:red"></i>'.html_safe, 
            post, :title => "Delete post",  
            method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, :class => "btn btn-primary" %>

app/views/posts/new.html.erb
<h3>New Post</h3>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice" class="<%= 'alert alert-success' if notice %>"><%= notice %></p>

<h3><%= @post.title %></h3>
<p>
  <%= link_to image_tag(@post.user.picture, class: "rounded-circle", size: "23"), {action: 'mypage', controller: 'users'} %>
  <small style="color: grey;">
    <%= if @post.published_at?
        @post.published_at 
      else
        "Unpublished"
      end
    %>
  </small>
</p>
<%= @post.content %><br>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light rounded">
  <%= link_to("/", {:class => "navbar-brand"}) do %>
    <span class="fa fa-home fa-lg"></span>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" 
    aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample09">
    <ul class="navbar-nav  mr-auto">
      <li class="nav-item">
        <%= link_to 'Posts', posts_path, class: "nav-link" if user_signed_in? %>
      </li>
      <li class="nav-item">
        <%= link_to 'Users', users_path, class: "nav-link" if user_signed_in? and current_user.is_admin %>
      </li>
    </ul>
    <%=
      unless user_signed_in?
        link_to 'Sign in', login_path, class: "nav-link, dropdown" 
      else
        link_to image_tag(current_user.picture, class: "rounded", size: "38"), {action: 'mypage', controller: 'users'}
      end
      %>
  </div>
</nav>

app/views/shared/_navbar2.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" >
    <%= form.text_field :provider, class: 'form-control', placeholder: "Provider" %>
  </div>

  <div class="field">
    <%= form.text_field :uid, class: 'form-control', placeholder: "UID" %>
  </div>

  <div class="field">
    <%= form.text_field :email, class: 'form-control', placeholder: "Email" %>
  </div>

  <div class="field">
    <%= form.text_field :first_name, class: 'form-control', placeholder: "First name" %>
  </div>

  <div class="field">
    <%= form.text_field :last_name, class: 'form-control', placeholder: "Last name" %>
  </div>

  <div class="field">
    <%= form.text_field :picture, class: 'form-control', placeholder: "Picture" %>
  </div>

  <div class="field custom-control custom-switch">
    <%= form.check_box :is_admin, :id => "is_admin", :class => "form-control custom-control-input" %>
    <%= form.label :Admin, :class=> "custom-control-label", :for => "is_admin"%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3>Editing User</h3>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Manage Users</h3>

<table class="table table-sm">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Provider</th>
      <th>Uid</th>
      <th>Email</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag(user.picture, class: "rounded", size: 25) %></td>
        <td><%= user.first_name + " " + user.last_name %></td>
        <td><%= user.provider %></td>
        <td><%= user.uid %></td>
        <td><%= user.email %></td>
        <td class="text-center">
          <% if user.is_admin? %>
            <i class="material-icons" style="color:orange" title="Admin">stars</i>
          <% end %>
        </td>
        <td><%= link_to '<i class="fa fa-eye" style="color:green"></i>'.html_safe, user %></td>
        <td><%= link_to '<i class="fa fa-edit" style="color:blue"></i>'.html_safe, edit_user_path(user) %></td>
        <td><%= link_to '<i class="fa fa-trash" style="color:red"></i>'.html_safe, 
          user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/mypage.html.erb
<h3> Hello <%= current_user.first_name if user_signed_in? %></h3>

<% if user_signed_in? %>
	<% current_user.attributes.each do |k, v| %>
		<b><%= k %>:</b> <%= v %> <br>
    <% end %>
    <br>
    <%= link_to 'Sign out', logout_path, :class => "btn btn-warning btn-sm" %>
<% end %>

app/views/users/new.html.erb
<h3>New User</h3>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provider:</strong>
  <%= @user.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @user.uid %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @user.picture %>
</p>

<p>
  <strong>Is admin:</strong>
  <%= @user.is_admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>